[program:saslauthd]
command=/usr/sbin/saslauthd -a ldap -V -c -m /var/run/saslauthd -d
directory=/var/run/saslauthd
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10
